// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:eba6b3a8-3edc-4314-8699-61a4be5a701c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_g6Y4Ft1b1",
    "aws_user_pools_web_client_id": "6kmlp2b9navg2ffoi68sig3f3s",
    "oauth": {}
};


export default awsmobile;
