package com.pag.modelo;

import java.util.List;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
@DynamoDBTable(tableName = "pedido")
public class Pedido {
	

	private Double valor;
	private List<Item> itens;
	@Id
	private PedidoId pedidoId = new PedidoId();
	
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return pedidoId.getId();
	}
	
	public void setId(String id) {
		pedidoId.setId(id);
	}
	
	@DynamoDBRangeKey(attributeName = "id_cliente")
	public String getCliente() {
		return pedidoId.getIdCliente();
	}
	
	public void setCliente(String idCliente) {
		pedidoId.setIdCliente(idCliente);
	}
	
	@DynamoDBAttribute(attributeName = "valor")
	public Double getValor() {
		return valor;
	}
	
	public void setValor(Double valor) {
		this.valor = valor;
	}
	
	public void setItens(List<Item> itens) {
		this.itens = itens;
	}
	
	@DynamoDBAttribute(attributeName = "itens")
	public List<Item> getItens() {
		return itens;
	}
	
}
