package com.pag.modelo;

import javax.validation.constraints.Size;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "produto")
public class Produto{


	
	private String id;
	@Size(max = 100, message = "O nome não pode ser superior a 100 caracteres")
	private String nome;
	private Double precoSugerido;

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute(attributeName = "nome")
	public String getNome() {
		return nome;
	}
	
	public void setNome(String nome) {
		this.nome = nome;
	}
	
	@DynamoDBAttribute(attributeName = "preco_sugerido")
	public Double getPrecoSugerido() {
		return precoSugerido;
	}
	
	public void setPrecoSugerido(Double precoSugerido) {
		this.precoSugerido = precoSugerido;
	}


	
	
}
