//CLIENTES
GET http://localhost:8080/clientes/David/12345678989
content-type: application/json
Authorization: Basic test pass

###

POST http://localhost:8080/clientes HTTP/1.1
content-type: application/json
Authorization: Basic test pass

{
    "nome":"Teste",
    "cpf":"12345678989",
    "dataNascimento":"2019-04-04"
}

###

PUT http://localhost:8080/clientes/14 HTTP/1.1
content-type: application/json
Authorization: Basic test pass

{
    "nome":"Cliente 99",
    "cpf":"89991678912",
    "dataNascimento":"2019-02-04"
}

###

DELETE http://localhost:8080/clientes/55
content-type: application/json
Authorization: Basic test pass
###

//PEDIDOS
GET http://localhost:8080/pedidos/14
content-type: application/json

###

POST http://localhost:8080/pedidos HTTP/1.1
content-type: application/json

{
    "idCliente": "14",
    "valor": "1124.55"
}

###

PUT http://localhost:8080/pedidos/14 HTTP/1.1
content-type: application/json
Authorization: Basic test pass

{
    "idCliente": "14",
    "valor": "14.55"
}

###

DELETE http://localhost:8080/pedidos/9
content-type: application/json

###
POST http://localhost:8080/produtos HTTP/1.1
content-type: application/json
Authorization: Basic test pass

{
    "nome": "Produto 20",
    "precoSugerido": "62.95"
}